const typeNameEs = {
  normal: "Normal",
  fire: "Fuego",
  water: "Agua",
  electric: "Eléctrico",
  grass: "Planta",
  ice: "Hielo",
  fighting: "Lucha",
  poison: "Veneno",
  ground: "Tierra",
  flying: "Volador",
  psychic: "Psíquico",
  bug: "Bicho",
  rock: "Roca",
  ghost: "Fantasma",
  dragon: "Dragón",
  dark: "Siniestro",
  steel: "Acero",
  fairy: "Hada",
};

const typeColorEsp = {
  Normal: "#A8A77A",
  Fuego: "#EE8130",
  Agua: "#6390F0",
  Eléctrico: "#F7D02C",
  Planta: "#7AC74C",
  Hielo: "#96D9D6",
  Lucha: "#C22E28",
  Veneno: "#A33EA1",
  Tierra: "#E2BF65",
  Volador: "#A98FF3",
  Psíquico: "#F95587",
  Bicho: "#A6B91A",
  Roca: "#B6A136",
  Fantasma: "#735797",
  Dragón: "#6F35FC",
  Siniestro: "#705746",
  Acero: "#B7B7CE",
  Hada: "#D685AD",
};

const colours = {
  normal: "#A8A77A",
  fire: "#EE8130",
  water: "#6390F0",
  electric: "#F7D02C",
  grass: "#7AC74C",
  ice: "#96D9D6",
  fighting: "#C22E28",
  poison: "#A33EA1",
  ground: "#E2BF65",
  flying: "#A98FF3",
  psychic: "#F95587",
  bug: "#A6B91A",
  rock: "#B6A136",
  ghost: "#735797",
  dragon: "#6F35FC",
  dark: "#705746",
  steel: "#B7B7CE",
  fairy: "#D685AD",
};

const pokedexEs = {
  "national": "Nacional",
  "kanto": "Kanto",
  "original-johto": "Original Johto",
  "hoenn": "Original Hoenn",
  "original-sinnoh": "Original Sinnoh",
  "extended-sinnoh": "Extended Sinnoh",
  "updated-johto": "Updated Johto",
  "original-unova": "Original Unova",
  "updated-unova": "Updated Unova",
  "conquest-gallery": "Gallery",
  "kalos-central": "Central Kalos",
  "kalos-coastal": "Coastal Kalos",
  "kalos-mountain": "Mountain Kalos ",
  "updated-hoenn": "New Hoenn",
  "original-alola": "Original Alola",
  "original-melemele": "Original Melemele",
  "original-akala": "Original Akala",
  "original-ulaula": "Original Ula'ula",
  "original-poni": "Original Poni",
  "updated-alola": "Updated Alola",
  "updated-melemele": "Updated Melemele",
  "updated-akala": "Updated Akala",
  "updated-ulaula": "Updated Ula'ula",
  "updated-poni": "Updated Poni",
  "letsgo-kanto": "Let’s Go Kanto",
  "galar": "Galar",
  "isle-of-armor": "Isle of Armor",
  "crown-tundra": "Crown Tundra",
  "hisui": "Hisui",
  "paldea": "Paldea",
  "kitakami": "Kitakami",
  "blueberry": "Paldea"
};

const statsEs = {
  "hp": "PS",
  "attack": "Ataque",
  "defense": "Defensa",
  "special-attack": "Atq. Especial",
  "special-defense": "Def. Especial",
  "speed": "Velocidad",
  "accuracy": "Precisión",
  "evasion": "Evasión",
};

const evoItems = {
  "sun-stone": "Piedra Solar",
  "moon-stone": "Piedra Lunar",
  "fire-stone": "Piedra Fuego",
  "thunder-stone": "Piedra Trueno",
  "water-stone": "Piedra Agua",
  "leaf-stone": "Piedra Hoja",
  "shiny-stone": "Piedra Día",
  "dusk-stone": "Piedra Noche",
  "dawn-stone": "Piedra Alba",
  "oval-stone": "Piedra Oval",
  "dragon-scale": "Escama Dragón",
  "up-grade": "Mejora",
  "protector": "Protector",
  "electirizer": "Electrizador",
  "magmarizer": "Magmatizador",
  "dubious-disc": "Disco Extraño",
  "reaper-cloth": "Tela Terrible",
  "prism-scale": "Escama Bella",
  "whipped-dream": "Dulce de Nata",
  "sachet": "Saquito Fragante",
  "ice-stone": "Piedra Hielo",
  "strawberry-sweet": "Confite Fresa",
  "love-sweet": "Confite Corazón",
  "berry-sweet": "Confite Fruto",
  "clover-sweet": "Confite Trébol",
  "flower-sweet": "Confite Flor",
  "star-sweet": "Confite Estrella",
  "ribbon-sweet": "Confite Lazo",
  "sweet-apple": "Manzana Dulce",
  "tart-apple": "Manzana Ácida",
  "cracked-pot": "Tetera Agrietada",
  "chipped-pot": "Tetera Rota",
  "malicious-armor": "sin traducción",
  "syrupy-apple": "sin traducción",
  "unremarkable-teacup": "sin traducción",
  "masterpiece-teacup": "sin traducción",
  "linking-cord": "sin traducción",
  "black-augurite": "sin traducción",
  "peat-block": "sin traducción",
};

export { typeNameEs, typeColorEsp, colours, pokedexEs, statsEs, evoItems };
